import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Box, Grid } from 'theme-ui'

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>The Trail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{backgroundColor: "#FFF5D8", height: "500vh"}}>
        <img style={{position: "absolute", zIndex: 0, width: "100vw", minHeight: 208, objectFit: "cover"}} src="./TopSky.svg"/>
        <div style={{height: 116, flexDirection: "column", width: "100vw", display: "flex", alignItems: "center", justifyContent: "center", position: "absolute", top: 96}}>
          <div style={{width: "100vw", height: 16, backgroundColor: "#032412"}}></div>
          <div style={{width: "100vw", height: 8, marginTop: 8, backgroundColor: "#032412"}}></div>
          <div style={{width: "100vw", height: 4, marginTop: 4, backgroundColor: "#032412"}}></div>
          <div style={{width: "100vw", height: 2, marginTop: 2, backgroundColor: "#032412"}}></div>
          <div style={{width: "100vw", height: 1, marginTop: 1, backgroundColor: "#032412"}}></div>

        </div>
        <div style={{height: 116, width: "100vw", display: "flex", alignItems: "center", justifyContent: "center", position: "absolute", top: 96}}>
          <img style={{height: 116}} src="./Intergalatic.svg"/>
        </div>
        <Box sx={{paddingTop: 242, zIndex: 2, position: "relative"}}>
        <img style={{position: "absolute", width: 450, left: "calc(50% - 225px)"}} src="TheTrailType.svg"/>

        <Grid columns={["1fr 1fr"]} sx={{justifyContent: "space-between", backgroundColor: "#FFF5D8", marginLeft: [32, 128, 196, 256], marginRight: [32, 128, 196, 256], aspectRatio: '2', overflow: "hidden", border: '8px solid #032412'}}>
  <div style={{height: "calc(100% - 96px)", display: "flex", padding: 32, flexDirection: "column", justifyContent: "space-between", width: "calc(100% - 64px)"}}>
    <p style={{fontSize: 16, fontWeight: 300}}>PACIFIC CREST TRAIL, 2024</p>
    <div>
    <p style={{fontSize: 24, lineHeight: 2}}>Hey there,</p>
    <p style={{marginTop: 24, fontSize: 24, lineHeight: 1.5}}>
      You’re invited on a 7 day hike along the Pacific Crest Trail and a 4 week hiking equipment building event with 30 Hack Clubbers  
    </p>

    <p style={{fontSize: 24, lineHeight: 1.5, marginTop:  24}}>

    <i style={{fontSize: 36,letterSpacing: "1.5px", lineHeight: 1}} class="strange">Save the date:</i><br/>
    Hack & Hike: July 12 - July 19
    </p>
    </div>
    <div style={{display: "flex"}}>
    <div style={{marginTop: 16, alignItems: "center", display: "flex", justifyContent: "center"}}>
    <button style={{position: "absolute", fontSize: 24, fontFamily: "Fraunces", borderRadius: 0, backgroundColor: "#032412", border: "2px solid #FFF5D8", outline:"none", color:"#FFF5D8", padding: "16px 24px"}}>Hop Onboard</button>

    <button style={{fontSize: 24, fontFamily: "Fraunces", borderRadius: 0, backgroundColor: "#032412", border: "4px solid #032412", outline:"none", color:"#FFF5D8", padding: "16px 24px"}}>Hop Onboard</button>
    </div>
    </div>
  </div>
  <div style={{width: "100%", position:"relative", flexDirection: "column", height: "100%", display: "flex", justifyContent: "space-between"}}>

  <img style={{position: "absolute", width: 120, height: 120, right: 16, top:16}} src="TakeStamp.svg"/>
  <img style={{position: "absolute", width: 86, height: 86, right: 16, zIndex: 2, top:164}} src="beginnersWelcome.svg"/>

    <p></p>
    <div style={{objectFit: "fit", overflow: "hidden", width: "100%", position: "relative"}}>

    <img style={{objectFit: "fit", overflow: "hidden", width: "100%"}} src="./rightHalf.svg"/>

      </div>

  </div>
</Grid>

        </Box>


        {/* <p>Hello World!</p> */}
      </main>
    </>
  );
}
